"""add review_snapshots (align with llm.py)

Revision ID: 4a3fc2339c25
Revises: a461444bfcd9
Create Date: 2025-10-02 18:48:04.610653
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a3fc2339c25'
down_revision: Union[str, Sequence[str], None] = 'a461444bfcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_examples_persona_id'), table_name='review_examples')
    op.drop_index(op.f('ix_review_examples_style_key'), table_name='review_examples')
    op.drop_table('review_examples')

    # kind: AutoString -> String
    op.add_column('review_snapshots', sa.Column('kind', sa.String(), nullable=False))
    op.add_column('review_snapshots', sa.Column('style_id', sa.Integer(), nullable=True))

    op.alter_column('review_snapshots', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # payload_json: 길 수 있으므로 Text로 바꾸고 싶다면 existing_type만 수정해도 되고,
    # 여기서는 nullable만 변경 (자동생성 원형 유지)
    op.alter_column('review_snapshots', 'payload_json',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_index(op.f('ix_review_snapshots_prompt_key'), table_name='review_snapshots')
    op.drop_index(op.f('ix_review_snapshots_style_key'), table_name='review_snapshots')

    op.create_index(op.f('ix_review_snapshots_kind'), 'review_snapshots', ['kind'], unique=False)
    op.create_index(op.f('ix_review_snapshots_style_id'), 'review_snapshots', ['style_id'], unique=False)
    op.create_foreign_key(None, 'review_snapshots', 'style_catalog', ['style_id'], ['id'])

    op.drop_column('review_snapshots', 'prompt_key')
    op.drop_column('review_snapshots', 'style_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_snapshots', sa.Column('style_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('review_snapshots', sa.Column('prompt_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    op.drop_constraint(None, 'review_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_review_snapshots_style_id'), table_name='review_snapshots')
    op.drop_index(op.f('ix_review_snapshots_kind'), table_name='review_snapshots')

    op.create_index(op.f('ix_review_snapshots_style_key'), 'review_snapshots', ['style_key'], unique=False)
    op.create_index(op.f('ix_review_snapshots_prompt_key'), 'review_snapshots', ['prompt_key'], unique=False)

    op.alter_column('review_snapshots', 'payload_json',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.alter_column('review_snapshots', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_column('review_snapshots', 'style_id')
    op.drop_column('review_snapshots', 'kind')

    op.create_table(
        'review_examples',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('style_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('review_examples_persona_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('review_examples_pkey'))
    )
    op.create_index(op.f('ix_review_examples_style_key'), 'review_examples', ['style_key'], unique=False)
    op.create_index(op.f('ix_review_examples_persona_id'), 'review_examples', ['persona_id'], unique=False)
    # ### end Alembic commands ###

