
"""add review_examples & review_snapshots

Revision ID: a461444bfcd9
Revises: 33ff01e7bbf8
Create Date: 2025-10-02 14:32:07.197683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a461444bfcd9'
down_revision: Union[str, Sequence[str], None] = '33ff01e7bbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'review_chat_messages',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'review_chat_messages',
        'content',
        existing_type=sa.TEXT(),
        type_=sa.String(),   # <- AutoString -> sa.String
        existing_nullable=False
    )
    op.alter_column(
        'review_chat_messages',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False
    )
    op.drop_constraint(
        op.f('review_chat_messages_thread_id_fkey'),
        'review_chat_messages',
        type_='foreignkey'
    )
    op.create_foreign_key(
        None,
        'review_chat_messages',
        'review_chat_threads',
        ['thread_id'],
        ['id']
    )

    op.alter_column(
        'review_chat_threads',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False
    )
    op.drop_constraint(
        op.f('review_chat_threads_user_id_fkey'),
        'review_chat_threads',
        type_='foreignkey'
    )
    op.create_foreign_key(
        None,
        'review_chat_threads',
        'users',
        ['user_id'],
        ['id']
    )

    op.alter_column(
        'review_examples',
        'text',
        existing_type=sa.TEXT(),
        type_=sa.String(),   # <- AutoString -> sa.String
        existing_nullable=False
    )
    op.alter_column(
        'review_examples',
        'quality_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=True
    )
    op.alter_column(
        'review_examples',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False
    )

    op.alter_column(
        'review_snapshots',
        'payload_json',
        existing_type=sa.TEXT(),
        type_=sa.String(),   # <- AutoString -> sa.String
        existing_nullable=False
    )
    op.alter_column(
        'review_snapshots',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False
    )
    op.create_index(
        op.f('ix_review_snapshots_persona_id'),
        'review_snapshots',
        ['persona_id'],
        unique=False
    )

    op.alter_column(
        'users',
        'login_count',
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'login_count',
        existing_type=sa.INTEGER(),
        server_default=sa.text('0'),
        existing_nullable=False
    )

    op.drop_index(op.f('ix_review_snapshots_persona_id'), table_name='review_snapshots')

    op.alter_column(
        'review_snapshots',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text('now()'),
        existing_nullable=False
    )
    op.alter_column(
        'review_snapshots',
        'payload_json',
        existing_type=sa.String(),   # <- AutoString 였던 것과 대칭
        type_=sa.TEXT(),
        existing_nullable=False
    )

    op.alter_column(
        'review_examples',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text('now()'),
        existing_nullable=False
    )
    op.alter_column(
        'review_examples',
        'quality_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text('1.0'),
        existing_nullable=True
    )
    op.alter_column(
        'review_examples',
        'text',
        existing_type=sa.String(),   # <- AutoString 였던 것과 대칭
        type_=sa.TEXT(),
        existing_nullable=False
    )

    op.drop_constraint(None, 'review_chat_threads', type_='foreignkey')
    op.create_foreign_key(
        op.f('review_chat_threads_user_id_fkey'),
        'review_chat_threads',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.alter_column(
        'review_chat_threads',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text('now()'),
        existing_nullable=False
    )

    op.drop_constraint(None, 'review_chat_messages', type_='foreignkey')
    op.create_foreign_key(
        op.f('review_chat_messages_thread_id_fkey'),
        'review_chat_messages',
        'review_chat_threads',
        ['thread_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.alter_column(
        'review_chat_messages',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text('now()'),
        existing_nullable=False
    )
    op.alter_column(
        'review_chat_messages',
        'content',
        existing_type=sa.String(),   # <- AutoString 였던 것과 대칭
        type_=sa.TEXT(),
        existing_nullable=False
    )
    op.alter_column(
        'review_chat_messages',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    # ### end Alembic commands ###
