"""polish models: indexes & relations

Revision ID: bca4912595f5
Revises: 05ec69ee100b
Create Date: 2025-09-29 03:14:57.197469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bca4912595f5'
down_revision: Union[str, Sequence[str], None] = '05ec69ee100b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_prompt_templates_prompt_key'), 'review_prompt_templates', ['prompt_key'], unique=False)
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_drafts_persona_id'), 'review_drafts', ['persona_id'], unique=False)
    op.create_index(op.f('ix_review_drafts_request_id'), 'review_drafts', ['request_id'], unique=False)
    op.create_index(op.f('ix_review_drafts_style_id'), 'review_drafts', ['style_id'], unique=False)
    op.create_index(op.f('ix_review_drafts_user_id'), 'review_drafts', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_requests_persona_id'), 'review_requests', ['persona_id'], unique=False)
    op.create_index(op.f('ix_review_requests_style_id'), 'review_requests', ['style_id'], unique=False)
    op.create_index(op.f('ix_review_requests_user_id'), 'review_requests', ['user_id'], unique=False)
    op.drop_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', type_='unique')
    op.create_index(op.f('ix_user_profiles_closest_persona_id'), 'user_profiles', ['closest_persona_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_closest_style_id'), 'user_profiles', ['closest_style_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_style_samples_user_id'), 'user_style_samples', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_style_scores_style_id'), 'user_style_scores', ['style_id'], unique=False)
    op.create_index(op.f('ix_user_style_scores_user_id'), 'user_style_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_style_scores_user_id'), table_name='user_style_scores')
    op.drop_index(op.f('ix_user_style_scores_style_id'), table_name='user_style_scores')
    op.drop_index(op.f('ix_user_style_samples_user_id'), table_name='user_style_samples')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_closest_style_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_closest_persona_id'), table_name='user_profiles')
    op.create_unique_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_review_requests_user_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_style_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_persona_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_drafts_user_id'), table_name='review_drafts')
    op.drop_index(op.f('ix_review_drafts_style_id'), table_name='review_drafts')
    op.drop_index(op.f('ix_review_drafts_request_id'), table_name='review_drafts')
    op.drop_index(op.f('ix_review_drafts_persona_id'), table_name='review_drafts')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_index(op.f('ix_review_prompt_templates_prompt_key'), table_name='review_prompt_templates')
    op.drop_table('review_prompt_templates')
    # ### end Alembic commands ###
